// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMKB5br6vd2RSsD-c1SVrfXbnm5AxY6JQ',
    appId: '1:520555293473:web:7a07dd5ec5d2b082be2c60',
    messagingSenderId: '520555293473',
    projectId: 'elearning-c5dbb',
    authDomain: 'elearning-c5dbb.firebaseapp.com',
    storageBucket: 'elearning-c5dbb.firebasestorage.app',
    measurementId: 'G-438D0Z5DCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFy_GPLE4-PWsHaxe3qv-pbJiFMhj9Eg',
    appId: '1:520555293473:android:276c037bef315706be2c60',
    messagingSenderId: '520555293473',
    projectId: 'elearning-c5dbb',
    storageBucket: 'elearning-c5dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAsxTU5mDkJorNHwe4oTCdIfRWnngTQX8',
    appId: '1:520555293473:ios:5298bff529bc75c8be2c60',
    messagingSenderId: '520555293473',
    projectId: 'elearning-c5dbb',
    storageBucket: 'elearning-c5dbb.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAsxTU5mDkJorNHwe4oTCdIfRWnngTQX8',
    appId: '1:520555293473:ios:5298bff529bc75c8be2c60',
    messagingSenderId: '520555293473',
    projectId: 'elearning-c5dbb',
    storageBucket: 'elearning-c5dbb.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMKB5br6vd2RSsD-c1SVrfXbnm5AxY6JQ',
    appId: '1:520555293473:web:eea0809611bbdedebe2c60',
    messagingSenderId: '520555293473',
    projectId: 'elearning-c5dbb',
    authDomain: 'elearning-c5dbb.firebaseapp.com',
    storageBucket: 'elearning-c5dbb.firebasestorage.app',
    measurementId: 'G-RJRNP7H3KP',
  );
}
